api/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "grievances#index"
  resources :grievances,only: [:index, :new, :create, :show]
end

api/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

api/app/models/grievance.rb
class Grievance < ApplicationRecord
  validates :name, :aggriever, :grievance, presence: true
end

api/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

api/app/controllers/grievances_controller.rb
class GrievancesController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @grievances = Grievance.all
  end

  def new
    @grievance = Grievance.new
  end

  def create
    @grievance = Grievance.new(grievance_params)

    if @grievance.save
      redirect_to @grievance
    else
      render :new
    end
  end

  def show
    @grievance = Grievance.find(params[:id])
  end

  private

  def grievance_params
    params.require(:grievance).permit(:name, :aggriever, :grievance)
  end
end

api/app/views/grievances/index.html.erb
<%= stylesheet_link_tag "style" %>
<%= javascript_include_tag "application" %>

<h1 class="heading">“I got a lot of problems with your people. Now, you’re gonna hear about it…”</h1>
<h3 class="link"><%= link_to 'Add Grievance', new_grievance_path %></h3>
<br>
<div class="content">
  <% @grievances.each do |grievance| %>
    <div class="slide">
      <%= grievance.grievance + ' aggrieved by ' + grievance.name + ' and aggriever by ' + grievance.aggriever + ' on ' + grievance.created_at.strftime("%d/%m/%Y") %>
    </div>
  <% end %>
</div>

api/app/views/grievances/new.html.erb
<h1>New Grievance</h1>

<%= form_with model: @grievance do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% @grievance.errors.full_messages_for(:name).each do |message| %>
      <div style="color: red"><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :aggriever %><br>
    <%= form.text_field :aggriever %>
    <% @grievance.errors.full_messages_for(:aggriever).each do |message| %>
      <div style="color: red"><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :grievance %><br>
    <%= form.text_area :grievance %>
    <% @grievance.errors.full_messages_for(:grievance).each do |message| %>
      <div style="color: red"><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit 'Save to air' %>
  </div>
<% end %>

api/app/views/grievances/show.html.erb
<h3 class="link"><%= link_to 'View All Grievance', grievances_path %></h3>

<h1><%= @grievance.name %></h1>
<h3><%= @grievance.aggriever %></h3>
<p><%= @grievance.grievance %></p>